# RuboCop Configuration
# Customize this file to match your team's coding standards

plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'config/environments/**/*'
    - 'config/initializers/**/*'
    - 'config/puma.rb'
    - 'config/boot.rb'
    - 'config/application.rb'
    - 'config/environment.rb'
    - 'config.ru'
    - 'Rakefile'

# Metrics
Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Rails
Rails/I18nLocaleTexts:
  Enabled: false

Rails/OutputSafety:
  Enabled: true

# RSpec
RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 20

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**/*'

RSpec/DescribedClass:
  Exclude:
    - 'spec/controllers/concerns/ip_helper_spec.rb'

RSpec/AnyInstance:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/LeakyConstantDeclaration:
  Enabled: false

# Lint
Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'
    - 'spec/**/*'

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*'
